var dir_ca06b39efc5497340cedbb398ca1fe8b =
[
    [ "exception", "dir_95cb3f554bff52aead345edd9c4acfab.html", "dir_95cb3f554bff52aead345edd9c4acfab" ],
    [ "execution_policy", "dir_a5bf748fc0561ed900d6a7aad17483cf.html", "dir_a5bf748fc0561ed900d6a7aad17483cf" ],
    [ "interface", "dir_a284e24806990e010dc02df07566edbb.html", "dir_a284e24806990e010dc02df07566edbb" ],
    [ "matching", "dir_b06486e5564ec710fe9e9170c5ad79a9.html", "dir_b06486e5564ec710fe9e9170c5ad79a9" ],
    [ "query", "dir_69012f9fea81684d400b3affb4af6704.html", "dir_69012f9fea81684d400b3affb4af6704" ],
    [ "table", "dir_f2aefbada23b48a8b12a626d2a4fd051.html", "dir_f2aefbada23b48a8b12a626d2a4fd051" ],
    [ "utility", "dir_c4d022882ab02fee5cab9b4457bd1ce4.html", "dir_c4d022882ab02fee5cab9b4457bd1ce4" ],
    [ "configure.h", "configure_8h.html", "configure_8h" ],
    [ "DeviceBitPackingCodec.cu", "DeviceBitPackingCodec_8cu.html", null ],
    [ "DeviceBitPackingCodec.h", "DeviceBitPackingCodec_8h.html", "DeviceBitPackingCodec_8h" ],
    [ "DeviceBitPackingHelpers.cu", "DeviceBitPackingHelpers_8cu.html", "DeviceBitPackingHelpers_8cu" ],
    [ "DeviceBitPackingHelpers.h", "DeviceBitPackingHelpers_8h.html", "DeviceBitPackingHelpers_8h" ],
    [ "DeviceCodecFactory.cu", "DeviceCodecFactory_8cu.html", "DeviceCodecFactory_8cu" ],
    [ "DeviceCodecFactory.h", "DeviceCodecFactory_8h.html", "DeviceCodecFactory_8h" ],
    [ "DeviceCodecs.cu", "DeviceCodecs_8cu.html", null ],
    [ "DeviceCodecs.h", "DeviceCodecs_8h.html", "DeviceCodecs_8h" ],
    [ "DeviceCompositeCodec.cu", "DeviceCompositeCodec_8cu.html", null ],
    [ "DeviceCompositeCodec.h", "DeviceCompositeCodec_8h.html", [
      [ "DeviceCompositeCodec", "classGPUGenie_1_1DeviceCompositeCodec.html", "classGPUGenie_1_1DeviceCompositeCodec" ]
    ] ],
    [ "DeviceDeltaHelper.h", "DeviceDeltaHelper_8h.html", [
      [ "DeviceDeltaHelper", "structGPUGenie_1_1DeviceDeltaHelper.html", null ]
    ] ],
    [ "DeviceSerialCodec.cu", "DeviceSerialCodec_8cu.html", null ],
    [ "DeviceSerialCodec.h", "DeviceSerialCodec_8h.html", "DeviceSerialCodec_8h" ],
    [ "DeviceVarintCodec.cu", "DeviceVarintCodec_8cu.html", null ],
    [ "DeviceVarintCodec.h", "DeviceVarintCodec_8h.html", "DeviceVarintCodec_8h" ],
    [ "FileReader.cu", "FileReader_8cu.html", "FileReader_8cu" ],
    [ "FileReader.h", "FileReader_8h.html", "FileReader_8h" ],
    [ "genie.cu", "genie_8cu.html", "genie_8cu" ],
    [ "genie_errors.cu", "genie__errors_8cu.html", null ],
    [ "genie_errors.h", "genie__errors_8h.html", "genie__errors_8h" ],
    [ "heap_count.cu", "heap__count_8cu.html", "heap__count_8cu" ],
    [ "heap_count.h", "heap__count_8h.html", "heap__count_8h" ],
    [ "interface.cu", "interface_8cu.html", "interface_8cu" ],
    [ "interface.h", "interface_8h.html", "interface_8h" ],
    [ "inv_compr_table.cu", "inv__compr__table_8cu.html", null ],
    [ "inv_compr_table.h", "inv__compr__table_8h.html", [
      [ "inv_compr_table", "classGPUGenie_1_1inv__compr__table.html", "classGPUGenie_1_1inv__compr__table" ]
    ] ],
    [ "inv_list.cu", "inv__list_8cu.html", "inv__list_8cu" ],
    [ "inv_list.h", "inv__list_8h.html", [
      [ "inv_list", "classGPUGenie_1_1inv__list.html", "classGPUGenie_1_1inv__list" ]
    ] ],
    [ "inv_table.cu", "inv__table_8cu.html", null ],
    [ "inv_table.h", "inv__table_8h.html", "inv__table_8h" ],
    [ "knn.cu", "knn_8cu.html", "knn_8cu" ],
    [ "knn.h", "knn_8h.html", "knn_8h" ],
    [ "Logger.cu", "Logger_8cu.html", null ],
    [ "Logger.h", "Logger_8h.html", "Logger_8h" ],
    [ "match.cu", "match_8cu.html", "match_8cu" ],
    [ "match.h", "match_8h.html", "match_8h" ],
    [ "match_common.cu", "match__common_8cu.html", "match__common_8cu" ],
    [ "match_common.h", "match__common_8h.html", "match__common_8h" ],
    [ "match_device_utils.h", "match__device__utils_8h.html", "match__device__utils_8h" ],
    [ "match_integrated.cu", "match__integrated_8cu.html", "match__integrated_8cu" ],
    [ "match_integrated.h", "match__integrated_8h.html", "match__integrated_8h" ],
    [ "query.cu", "query_8cu.html", "query_8cu" ],
    [ "query.h", "query_8h.html", "query_8h" ],
    [ "scan.cu", "scan_8cu.html", "scan_8cu" ],
    [ "scan.h", "scan_8h.html", "scan_8h" ],
    [ "serialization.cu", "serialization_8cu.html", "serialization_8cu" ],
    [ "serialization.h", "serialization_8h.html", "serialization_8h" ],
    [ "Timing.h", "Timing_8h.html", "Timing_8h" ]
];