# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/hd1/home/luanwenhao/sesame/libGaLG_old/libGaLG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/hd1/home/luanwenhao/sesame/libGaLG_old/libGaLG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/hd1/home/luanwenhao/sesame/libGaLG_old/libGaLG/CMakeFiles /media/hd1/home/luanwenhao/sesame/libGaLG_old/libGaLG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/hd1/home/luanwenhao/sesame/libGaLG_old/libGaLG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GaLG

# Build rule for target.
GaLG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GaLG
.PHONY : GaLG

# fast build rule for target.
GaLG/fast:
	$(MAKE) -f src/CMakeFiles/GaLG.dir/build.make src/CMakeFiles/GaLG.dir/build
.PHONY : GaLG/fast

#=============================================================================
# Target rules for targets named test_inv_list

# Build rule for target.
test_inv_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_inv_list
.PHONY : test_inv_list

# fast build rule for target.
test_inv_list/fast:
	$(MAKE) -f test/CMakeFiles/test_inv_list.dir/build.make test/CMakeFiles/test_inv_list.dir/build
.PHONY : test_inv_list/fast

#=============================================================================
# Target rules for targets named test_inv_table

# Build rule for target.
test_inv_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_inv_table
.PHONY : test_inv_table

# fast build rule for target.
test_inv_table/fast:
	$(MAKE) -f test/CMakeFiles/test_inv_table.dir/build.make test/CMakeFiles/test_inv_table.dir/build
.PHONY : test_inv_table/fast

#=============================================================================
# Target rules for targets named test_raw_data

# Build rule for target.
test_raw_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_raw_data
.PHONY : test_raw_data

# fast build rule for target.
test_raw_data/fast:
	$(MAKE) -f test/CMakeFiles/test_raw_data.dir/build.make test/CMakeFiles/test_raw_data.dir/build
.PHONY : test_raw_data/fast

#=============================================================================
# Target rules for targets named test_tool_csv

# Build rule for target.
test_tool_csv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tool_csv
.PHONY : test_tool_csv

# fast build rule for target.
test_tool_csv/fast:
	$(MAKE) -f test/CMakeFiles/test_tool_csv.dir/build.make test/CMakeFiles/test_tool_csv.dir/build
.PHONY : test_tool_csv/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... GaLG"
	@echo "... test_inv_list"
	@echo "... test_inv_table"
	@echo "... test_raw_data"
	@echo "... test_tool_csv"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

