var namespaceGPUGenie =
[
    [ "_GPUGenie_Config", "structGPUGenie_1_1__GPUGenie__Config.html", "structGPUGenie_1_1__GPUGenie__Config" ],
    [ "_GPUGenie_Query_Data", "structGPUGenie_1_1__GPUGenie__Query__Data.html", "structGPUGenie_1_1__GPUGenie__Query__Data" ],
    [ "cpu_bad_alloc", "classGPUGenie_1_1cpu__bad__alloc.html", "classGPUGenie_1_1cpu__bad__alloc" ],
    [ "cpu_runtime_error", "classGPUGenie_1_1cpu__runtime__error.html", "classGPUGenie_1_1cpu__runtime__error" ],
    [ "DeviceBitPackingCodec", "classGPUGenie_1_1DeviceBitPackingCodec.html", "classGPUGenie_1_1DeviceBitPackingCodec" ],
    [ "DeviceBitPackingHelpers", "structGPUGenie_1_1DeviceBitPackingHelpers.html", null ],
    [ "DeviceBitPackingPrefixedCodec", "classGPUGenie_1_1DeviceBitPackingPrefixedCodec.html", "classGPUGenie_1_1DeviceBitPackingPrefixedCodec" ],
    [ "DeviceCodecFactory", "classGPUGenie_1_1DeviceCodecFactory.html", null ],
    [ "DeviceCompositeCodec", "classGPUGenie_1_1DeviceCompositeCodec.html", "classGPUGenie_1_1DeviceCompositeCodec" ],
    [ "DeviceCopyCodec", "classGPUGenie_1_1DeviceCopyCodec.html", "classGPUGenie_1_1DeviceCopyCodec" ],
    [ "DeviceCopyMultiblockCodec", "classGPUGenie_1_1DeviceCopyMultiblockCodec.html", "classGPUGenie_1_1DeviceCopyMultiblockCodec" ],
    [ "DeviceDeltaCodec", "classGPUGenie_1_1DeviceDeltaCodec.html", "classGPUGenie_1_1DeviceDeltaCodec" ],
    [ "DeviceDeltaHelper", "structGPUGenie_1_1DeviceDeltaHelper.html", null ],
    [ "DeviceIntegerCODEC", "classGPUGenie_1_1DeviceIntegerCODEC.html", "classGPUGenie_1_1DeviceIntegerCODEC" ],
    [ "DeviceSerialCodec", "classGPUGenie_1_1DeviceSerialCodec.html", "classGPUGenie_1_1DeviceSerialCodec" ],
    [ "DeviceVarintCodec", "classGPUGenie_1_1DeviceVarintCodec.html", "classGPUGenie_1_1DeviceVarintCodec" ],
    [ "genie_error", "classGPUGenie_1_1genie__error.html", "classGPUGenie_1_1genie__error" ],
    [ "gpu_bad_alloc", "classGPUGenie_1_1gpu__bad__alloc.html", "classGPUGenie_1_1gpu__bad__alloc" ],
    [ "gpu_runtime_error", "classGPUGenie_1_1gpu__runtime__error.html", "classGPUGenie_1_1gpu__runtime__error" ],
    [ "inv_compr_table", "classGPUGenie_1_1inv__compr__table.html", "classGPUGenie_1_1inv__compr__table" ],
    [ "inv_list", "classGPUGenie_1_1inv__list.html", "classGPUGenie_1_1inv__list" ],
    [ "inv_table", "classGPUGenie_1_1inv__table.html", "classGPUGenie_1_1inv__table" ],
    [ "query", "classGPUGenie_1_1query.html", "classGPUGenie_1_1query" ]
];