var searchData=
[
  ['data_5f',['data_',['../structdata__.html',1,'']]],
  ['data_5ft',['data_t',['../structgenie_1_1matching_1_1data__t.html',1,'genie::matching']]],
  ['devicebitpackingcodec',['DeviceBitPackingCodec',['../classgenie_1_1compression_1_1DeviceBitPackingCodec.html',1,'genie::compression']]],
  ['devicebitpackinghelpers',['DeviceBitPackingHelpers',['../structgenie_1_1compression_1_1DeviceBitPackingHelpers.html',1,'genie::compression']]],
  ['devicebitpackingprefixedcodec',['DeviceBitPackingPrefixedCodec',['../classgenie_1_1compression_1_1DeviceBitPackingPrefixedCodec.html',1,'genie::compression']]],
  ['devicecodecfactory',['DeviceCodecFactory',['../classgenie_1_1compression_1_1DeviceCodecFactory.html',1,'genie::compression']]],
  ['devicecompositecodec',['DeviceCompositeCodec',['../classgenie_1_1compression_1_1DeviceCompositeCodec.html',1,'genie::compression']]],
  ['devicecopycodec',['DeviceCopyCodec',['../classgenie_1_1compression_1_1DeviceCopyCodec.html',1,'genie::compression']]],
  ['devicecopymultiblockcodec',['DeviceCopyMultiblockCodec',['../classgenie_1_1compression_1_1DeviceCopyMultiblockCodec.html',1,'genie::compression']]],
  ['devicedeltacodec',['DeviceDeltaCodec',['../classgenie_1_1compression_1_1DeviceDeltaCodec.html',1,'genie::compression']]],
  ['devicedeltahelper',['DeviceDeltaHelper',['../structgenie_1_1compression_1_1DeviceDeltaHelper.html',1,'genie::compression']]],
  ['deviceintegercodec',['DeviceIntegerCODEC',['../classgenie_1_1compression_1_1DeviceIntegerCODEC.html',1,'genie::compression']]],
  ['deviceintegratedblockpacker',['DeviceIntegratedBlockPacker',['../structgenie_1_1compression_1_1DeviceBitPackingCodec_1_1DeviceIntegratedBlockPacker.html',1,'genie::compression::DeviceBitPackingCodec']]],
  ['devicenodeltablockpacker',['DeviceNoDeltaBlockPacker',['../structgenie_1_1compression_1_1DeviceBitPackingCodec_1_1DeviceNoDeltaBlockPacker.html',1,'genie::compression::DeviceBitPackingCodec']]],
  ['deviceserialcodec',['DeviceSerialCodec',['../classgenie_1_1compression_1_1DeviceSerialCodec.html',1,'genie::compression']]],
  ['devicevarintcodec',['DeviceVarintCodec',['../classgenie_1_1compression_1_1DeviceVarintCodec.html',1,'genie::compression']]],
  ['dim',['dim',['../structgenie_1_1query_1_1Query_1_1dim.html',1,'genie::query::Query']]]
];
